# Generated by Django 4.0.3 on 2022-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0002_alter_instructor_certification_alter_instructor_demo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='certification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instructor',
            name='demo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='yoga_studio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
