# Generated by Django 4.0.3 on 2022-08-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_rest', '0003_instructor_email_alter_instructor_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='certification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instagram',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='yoga_studio',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
