# Generated by Django 4.0.3 on 2022-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_rest', '0002_alter_instructorvo_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorvo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructorvo',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
