# Generated by Django 4.0.3 on 2022-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes_rest', '0006_remove_studentvo__class_class_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorvo',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='instructorvo',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
